### ISSUE TITLE
float(django.get_version()) causes ValueError: could not convert string to float: '3.2.16'

### ISSUE THREAD

**Issue by stanim** [littlepea/django-docs#38]
This happens using sphinx autodoc in docs/views.py", line 18, see traceback:
WARNING: autodoc: failed to import module 'urls' from module 'project'; the following exception was raised:
```
Traceback (most recent call last):
  File "~/.virtualenvs/project/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/Sync/Laptop/zzp/go2people/local/project/src/project/project/urls.py", line 74, in <module>
    path(settings.DOCS_URL, include('docs.urls')),
  File "~/.virtualenvs/project/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/.virtualenvs/project/lib/python3.6/site-packages/docs/urls.py", line 2, in <module>
    from docs.views import DocsRootView, serve_docs, DOCS_DIRHTML
  File "~/.virtualenvs/project/lib/python3.6/site-packages/docs/views.py", line 18, in <module>
    if float(django.get_version())>=3:
ValueError: could not convert string to float: '3.2.16'
```

**Comment by stanim** [comment]
Downgrading django-docs to 0.3.1 solves the issue.

**Comment by amejia-et** [comment]
Same problem with python 3.10, Django 3.2.16 and django-docs 0.3.2
Downgrading also works for me.

**Comment by littlepea** [comment]
Published a new version: https://pypi.org/project/django-docs/0.3.3/
